OSS:
  ENDPOINT: ""
  ACCESS_KEY_ID: ""
  ACCESS_KEY_SECRET: ""
  BUCKET_NAME: ""

MongoDB:
  MONGODB_URL: "mongodb://localhost:27017"
  DATABASE: "SanguoImage"
  COLLECTION: "Metadata"

READ_FILEPATH: ""
LOCAL_FILE: ""